apiVersion: v1
kind: Service
metadata:
  name: taskmanagement
  namespace: devopsproject
spec:
  selector:
    app: taskmanagement
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

